config updated for karma server

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -44,6 +44,15 @@ jobs:
       - run:
           name: Run Unit Tests with Code Coverage
           command: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
+      - run:
+          name: Check Coverage Threshold
+          command: |
+            COVERAGE=$(grep -Po '"lines": \{"total":\d+,.*?"covered":\d+.*?"pct":\K\d+' coverage/coverage-summary.json)
+            echo "Code coverage is $COVERAGE%"
+            if [ "$COVERAGE" -lt 80 ]; then
+              echo "Code coverage is below 80%. Failing the pipeline."
+              exit 1
+            fi
       - persist_to_workspace:
           root: .
           paths:
@@ -80,8 +89,7 @@ jobs:
               -Dsonar.inclusions=src/**/*.ts \
               -Dsonar.exclusions=**/*.spec.ts \
               -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
-              -Dsonar.qualitygate.wait=true \
-              -Dsonar.coverage=80
+              -Dsonar.qualitygate.wait=true
 
 workflows:
   version: 2
